# FROM node:10-alpine as build-step
# RUN mkdir /app
# WORKDIR /app
# COPY package.json /app
# RUN npm install
# COPY . /app
# RUN npm run build

# FROM nginx:1.17.1-alpine
# COPY --from=build-step /app/build /usr/share/nginx/html

# build environment
FROM node:13.12.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
RUN npm install react-scripts@3.4.1 -g
COPY . ./

# Env vars for react need to be defined at build time, so we
# use docker args to set these values instead.
ARG REACT_APP_API_HOST
ARG REACT_APP_API_PORT
ARG REACT_APP_DEV_DEBUG_MODE
ENV REACT_APP_API_HOST $REACT_APP_API_HOST
ENV REACT_APP_API_PORT $REACT_APP_API_PORT
ENV REACT_APP_DEV_DEBUG_MODE $REACT_APP_DEV_DEBUG_MODE

RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]